# Generated by Django 3.0.5 on 2020-04-21 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultImage',
        ),
    ]
