# Generated by Django 3.0.5 on 2020-04-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntryImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Adicionada em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificada em')),
                ('image', models.ImageField(upload_to='entry_images', verbose_name='Imagem de entrada')),
                ('crop', models.BooleanField(default=True, verbose_name='Cortar')),
                ('resized', models.BooleanField(default=False, verbose_name='Redimencionada')),
                ('height', models.PositiveIntegerField(default=384, verbose_name='Altura')),
                ('width', models.PositiveIntegerField(default=384, verbose_name='Largura')),
            ],
            options={
                'verbose_name': 'Imagem de entrada',
                'verbose_name_plural': 'Imagems de entradas',
                'ordering': ['added_at'],
            },
        ),
    ]
